apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: splitttr
data:
  NEXT_PUBLIC_API_BASE_URL: "http://localhost:8080"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_Y2hlZXJmdWwtcmFjY29vbi03MC5jbGVyay5hY2NvdW50cy5kZXYk"

  QUARKUS_HTTP_CORS_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
  MP_JWT_VERIFY_PUBLICKEY_LOCATION: "https://cheerful-raccoon-70.clerk.accounts.dev/.well-known/jwks.json"
  MP_JWT_VERIFY_PUBLICKEY_ALGORITHM: "RS256"
  MP_JWT_VERIFY_ISSUER: "https://cheerful-raccoon-70.clerk.accounts.dev"

  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/drive"
  QUARKUS_DATASOURCE_USERNAME: "drive"
  QUARKUS_DATASOURCE_PASSWORD: "drive"

  DOC_SERVICE_URL: "http://mdb-service:8081"

  APP_S3_ENDPOINT: "http://minio:9000"
  APP_S3_REGION: "us-east-1"
  APP_S3_ACCESS_KEY: "minio"
  APP_S3_SECRET_KEY: "minio12345"
  APP_S3_BUCKET: "drive-bucket"

  QUARKUS_MONGODB_CONNECTION_STRING: "mongodb://mongo:27017"
  QUARKUS_MONGODB_DATABASE: "splitttr"

  DOC_STORE_URL: "http://mdb-service:8081"
