apiVersion: v1
kind: Service
metadata:
  name: mdb-service
  namespace: splitttr
spec:
  selector:
    app: mdb-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdb-service
  namespace: splitttr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdb-service
  template:
    metadata:
      labels:
        app: mdb-service
    spec:
      containers:
        - name: mdb-service
          image: splitttr/mdb-service:local
          ports:
            - containerPort: 8081
          env:
            - name: QUARKUS_HTTP_PORT
              value: "8081"
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: QUARKUS_MONGODB_CONNECTION_STRING
            - name: QUARKUS_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: QUARKUS_MONGODB_DATABASE
