apiVersion: v1
kind: Service
metadata:
  name: docs-service
  namespace: splitttr
spec:
  selector:
    app: docs-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-service
  namespace: splitttr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs-service
  template:
    metadata:
      labels:
        app: docs-service
    spec:
      containers:
        - name: docs-service
          image: splitttr/docs-service:local
          ports:
            - containerPort: 8082
          env:
            - name: QUARKUS_HTTP_PORT
              value: "8082"
            - name: DOC_STORE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DOC_STORE_URL
