version: '3.8'
services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  document-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://mongodb:27017
      QUARKUS_MONGODB_DATABASE: docsdb
      QUARKUS_HTTP_CORS: "true"
      QUARKUS_HTTP_CORS_ORIGINS: "/.*/,http://localhost:5500,http://127.0.0.1:5500"
      QUARKUS_HTTP_CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      QUARKUS_HTTP_CORS_HEADERS: "Content-Type,Authorization"
    depends_on:
      - mongodb

volumes:
  mongo_data: